### ISSUE TITLE
Consume as remote release

### ISSUE THREAD

**Issue by gerhard** [emalm/tmux-boshrelease#1]
I would like to consume this release remotely. Would you be willing to add SHA1 & tgz to the Github release, similar to https://github.com/rabbitmq/rabbitmq-server-boshrelease/releases/tag/v0.9.0 ?

Publishing to bosh.io would help with discoverability, but it's not as important as the first point.

**Comment by emalm** [comment]
Hi, @gerhard,

Sure thing, I've created a [v0.0.1 GitHub release](https://github.com/emalm/tmux-boshrelease/releases/tag/v0.0.1) with the release tarball and `shasum` output attached.

Getting the release listed on [bosh.io](https://bosh.io) is ultimately up to @cppforlife to decide, but I'm game if he is. :)

Best,
Eric

**Comment by gerhard** [comment]
Thanks! Already added it to 2 deployments, works a treat 😉

**Comment by emalm** [comment]
Awesome, thanks for letting me know, and for providing the feedback!
